services:
  # --- Bases de donnees ---

  mongo-auth:
    image: mongo:4.4
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - backend
    restart: on-failure

  mongo-products:
    image: mongo:4.4
    volumes:
      - mongo-products-data:/data/db
    networks:
      - backend
    restart: on-failure

  mongo-orders:
    image: mongo:4.4
    volumes:
      - mongo-orders-data:/data/db
    networks:
      - backend
    restart: on-failure

  # --- Services backend ---

  auth-service:
    build:
      context: ./services/auth-service
      target: production
    image: auth-service:latest
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo-auth:27017/auth
      - JWT_SECRET=${JWT_SECRET:-efrei_super_pass}
      - NODE_ENV=production
    depends_on:
      - mongo-auth
    networks:
      - backend
    restart: on-failure

  product-service:
    build:
      context: ./services/product-service
      target: production
    image: product-service:latest
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo-products:27017/ecommerce
      - JWT_SECRET=${JWT_SECRET:-efrei_super_pass}
      - NODE_ENV=production
    depends_on:
      - mongo-products
    networks:
      - backend
    restart: on-failure

  order-service:
    build:
      context: ./services/order-service
      target: production
    image: order-service:latest
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongo-orders:27017/orders
      - JWT_SECRET=${JWT_SECRET:-efrei_super_pass}
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - NODE_ENV=production
    depends_on:
      - mongo-orders
    networks:
      - backend
    restart: on-failure

  # --- Frontend ---

  frontend:
    build:
      context: ./frontend
      target: production
    image: frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - backend
    restart: on-failure

volumes:
  mongo-auth-data:
  mongo-products-data:
  mongo-orders-data:

networks:
  backend:
    driver: bridge